// <auto-generated />
using System;
using HavingFun.EFDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HavingFun.EFDAL.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20190923225555_ProductsTablesAdded")]
    partial class ProductsTablesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HavingFun.EFDAL.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Attachment","schProducts");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Claims","schUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "CanSeeUsersList",
                            Value = "Allow"
                        });
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("ThumbnailId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Product","schProducts");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.ProductAttachment", b =>
                {
                    b.Property<int>("AttachmentId");

                    b.Property<int>("ProductId");

                    b.HasKey("AttachmentId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttachment","schProducts");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<int>("ParentCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductCategory","schProducts");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Roles","schUsers");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .HasMaxLength(256);

                    b.Property<bool>("IsActivated");

                    b.Property<string>("LastName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Users","schUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "karolas-borys@wp.pl",
                            FirstName = "Karol",
                            IsActivated = true,
                            LastName = "LatkaAdmin",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Username = "KarolAdmin"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "karolas-borys2@wp.pl",
                            FirstName = "Karol",
                            IsActivated = true,
                            LastName = "LatkaRegular",
                            PasswordHash = "effcc54ba75fb84cca1aadb6cae302e84c29dcb550e6e19e99c4916b89c69e0b",
                            Username = "Karol"
                        });
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.UserClaims", b =>
                {
                    b.Property<int>("ClaimId");

                    b.Property<int>("UserId");

                    b.HasKey("ClaimId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims","schUsers");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.UserRoles", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles","schUsers");
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.Product", b =>
                {
                    b.HasOne("HavingFun.EFDAL.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HavingFun.EFDAL.Entities.Attachment", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.ProductAttachment", b =>
                {
                    b.HasOne("HavingFun.EFDAL.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HavingFun.EFDAL.Entities.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.ProductCategory", b =>
                {
                    b.HasOne("HavingFun.EFDAL.Entities.ProductCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.UserClaims", b =>
                {
                    b.HasOne("HavingFun.EFDAL.Entities.Claim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HavingFun.EFDAL.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HavingFun.EFDAL.Entities.UserRoles", b =>
                {
                    b.HasOne("HavingFun.EFDAL.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HavingFun.EFDAL.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
